import { Model } from '@nozbe/watermelondb'
import { field, date, readonly } from '@nozbe/watermelondb/decorators'

export default class FinancialTransaction extends Model {
    static table = 'financial_transactions'

    @field('show_id') showId!: string
    @field('category') category!: string
    @field('description') description!: string
    @field('amount') amount!: number
    @field('transaction_date') transactionDate!: string
    @field('receipt_url') receiptUrl?: string
    @field('is_auto_generated') isAutoGenerated!: boolean

    @readonly @date('created_at') createdAt!: Date
    @readonly @date('updated_at') updatedAt!: Date
}
