"""fase_15_dynamism

Revision ID: 166716aa8cad
Revises: 1ddf4abb3e05
Create Date: 2026-02-24 19:34:45.579228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '166716aa8cad'
down_revision: Union[str, None] = '1ddf4abb3e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_checkins', sa.Column('dynamic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dados dinâmicos do formulário customizado (ex: placa, km, foto)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_checkins', 'dynamic_data')
    # ### end Alembic commands ###
