"""add_crm_models_and_sellers

Revision ID: 1ddf4abb3e05
Revises: 2d327a0323ba
Create Date: 2026-02-24 15:12:12.844008
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = '1ddf4abb3e05'
down_revision: str | None = '2d327a0323ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='O conteúdo da nota comercial'),
    sa.Column('author_id', sa.UUID(), nullable=True, comment='Usuário que registrou a nota'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_notes_contractor_id'), 'contractor_notes', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_notes_tenant_id'), 'contractor_notes', ['tenant_id'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome completo do vendedor'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='ID do usuário caso o vendedor use a plataforma'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_tenant_id'), 'sellers', ['tenant_id'], unique=False)
    op.create_table('commercial_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_name', sa.String(length=255), nullable=False, comment='Nome do contratante (pode não estar cadastrado ainda)'),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.String(length=50), nullable=True, comment='Data pretendida (string livre ou formatada)'),
    sa.Column('estimated_budget', sa.Numeric(precision=14, scale=2), nullable=True, comment='Orçamento previsto do cliente'),
    sa.Column('status', sa.Enum('PROSPECÇÃO', 'CONTATO', 'NEGOCIAÇÃO', 'GANHO', 'PERDIDO', name='commercial_lead_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_leads_tenant_id'), 'commercial_leads', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commercial_leads_tenant_id'), table_name='commercial_leads')
    op.drop_table('commercial_leads')
    op.drop_index(op.f('ix_sellers_tenant_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_contractor_notes_tenant_id'), table_name='contractor_notes')
    op.drop_index(op.f('ix_contractor_notes_contractor_id'), table_name='contractor_notes')
    op.drop_table('contractor_notes')
    # ### end Alembic commands ###
