"""create_document_templates_table

Revision ID: 2d327a0323ba
Revises: 4456e0ffe21d
Create Date: 2026-02-24 14:56:05.870870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '2d327a0323ba'
down_revision: Union[str, None] = '4456e0ffe21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Ex: 'Proposta Comercial Atitude 67' ou 'Minuta Padrão'"),
    sa.Column('entity_type', sa.Enum('SHOW', 'ARTIST', 'CONTRACTOR', name='document_entity_type'), nullable=False, comment='SHOW, ARTIST ou CONTRACTOR — define o objeto principal injetado'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='O HTML com as variáveis Jinja2 para renderização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_templates_tenant_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
