"""fase_26_ciclo_empenho_comprovacao

Revision ID: 30bf62668b0c
Revises: 87fbaf251c4b
Create Date: 2026-02-25 21:46:41.176208
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = '30bf62668b0c'
down_revision: str | None = '87fbaf251c4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_execution_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False, comment='URL da mídia no S3'),
    sa.Column('media_type', sa.String(length=50), nullable=False, comment='MIME type (image/jpeg, video/mp4, etc.)'),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_execution_media_show_id'), 'show_execution_media', ['show_id'], unique=False)
    op.create_index(op.f('ix_show_execution_media_tenant_id'), 'show_execution_media', ['tenant_id'], unique=False)
    op.add_column('financial_transactions', sa.Column('public_payment_status', sa.Enum('PENDING_EMPENHO', 'EMPENHADO', 'LIQUIDADO', 'PAGO', name='public_payment_status'), nullable=True, comment='Status do ciclo de empenho (apenas para mercado público)'))
    op.add_column('financial_transactions', sa.Column('empenho_date', sa.Date(), nullable=True, comment='Data da nota de empenho'))
    op.add_column('financial_transactions', sa.Column('empenho_number', sa.String(length=50), nullable=True, comment='Número da nota de empenho'))
    op.add_column('financial_transactions', sa.Column('liquidation_date', sa.Date(), nullable=True, comment='Data da liquidação'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_transactions', 'liquidation_date')
    op.drop_column('financial_transactions', 'empenho_number')
    op.drop_column('financial_transactions', 'empenho_date')
    op.drop_column('financial_transactions', 'public_payment_status')
    op.drop_index(op.f('ix_show_execution_media_tenant_id'), table_name='show_execution_media')
    op.drop_index(op.f('ix_show_execution_media_show_id'), table_name='show_execution_media')
    op.drop_table('show_execution_media')
    # ### end Alembic commands ###
