"""expand_tenant_fields

Revision ID: 323c2aa8f611
Revises: 30bf62668b0c
Create Date: 2026-02-27 15:36:54.326643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic
revision: str = '323c2aa8f611'
down_revision: Union[str, None] = '30bf62668b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Colunas faltantes em tenants ###
    op.add_column('tenants', sa.Column('cnpj', sa.String(length=20), nullable=True, comment='CNPJ oficial da agência'))
    op.create_unique_constraint('uq_tenants_cnpj', 'tenants', ['cnpj'])
    op.add_column('tenants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('plan_type', sa.String(length=50), server_default='Essencial', nullable=False))
    op.add_column('tenants', sa.Column('feature_toggles', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tenants', sa.Column('max_storage_gb', sa.Integer(), server_default='10', nullable=False))
    op.add_column('tenants', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_suspended')
    op.drop_column('tenants', 'max_storage_gb')
    op.drop_column('tenants', 'feature_toggles')
    op.drop_column('tenants', 'plan_type')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_name')
    op.drop_column('tenants', 'address')
    op.drop_constraint('uq_tenants_cnpj', 'tenants', type_='unique')
    op.drop_column('tenants', 'cnpj')
    # ### end Alembic commands ###
