"""add_leads_tickets_ticket_replies

Revision ID: 4456e0ffe21d
Revises: f2ef7a1580d7
Create Date: 2026-02-23 17:18:26.591141
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = '4456e0ffe21d'
down_revision: str | None = 'f2ef7a1580d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Nome do escritório/produtora prospectado'),
    sa.Column('contact_name', sa.String(length=255), nullable=False, comment='Nome do contato principal'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CNPJ ou CPF'),
    sa.Column('status', sa.Enum('NOVO', 'CONTATADO', 'QUALIFICADO', 'PROPOSTA', 'CONVERTIDO', 'PERDIDO', name='lead_status'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True, comment='Origem do lead (Site, Indicação, Instagram, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações sobre o lead'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Produtora que abriu o chamado'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Usuário que abriu o chamado'),
    sa.Column('subject', sa.String(length=255), nullable=False, comment='Assunto do chamado'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descrição detalhada do problema'),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ATENDIMENTO', 'RESOLVIDO', 'FECHADO', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='ticket_priority'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Categoria (Financeiro, Técnico, Sugestão, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_table('ticket_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False, comment='Nome do autor da resposta (equipe ou cliente)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Conteúdo da resposta'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='Se True, resposta interna da equipe (não visível para o cliente)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_replies_ticket_id'), 'ticket_replies', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_replies_ticket_id'), table_name='ticket_replies')
    op.drop_table('ticket_replies')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('leads')
    # ### end Alembic commands ###
