"""feat_visibility_matrix_level_3

Revision ID: 527d7823a2c6
Revises: c3ca71e494ff
Create Date: 2026-02-25 19:28:46.036390
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = '527d7823a2c6'
down_revision: str | None = 'c3ca71e494ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_artists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    op.add_column('users', sa.Column('has_global_artist_access', sa.Boolean(), server_default='false', nullable=False, comment='Se True, ignora a tabela de associação e vê todos os artistas do tenant'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_global_artist_access')
    op.drop_table('user_artists')
    # ### end Alembic commands ###
