"""feat_logistics_smart_fase_27

Revision ID: 7684d2a8db28
Revises: db9c308341ec
Create Date: 2026-02-25 20:19:45.934815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7684d2a8db28'
down_revision: Union[str, None] = 'db9c308341ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_timeline', sa.Column('weather_temp', sa.Numeric(precision=5, scale=2), nullable=True, comment='Temperatura prevista para o local/horário'))
    op.add_column('logistics_timeline', sa.Column('weather_condition', sa.String(length=100), nullable=True, comment='Condição climática (ex: Céu Limpo, Chuva Moderada)'))
    op.add_column('logistics_timeline', sa.Column('route_distance', sa.String(length=50), nullable=True, comment='Distância estimada (Google Maps)'))
    op.add_column('logistics_timeline', sa.Column('route_duration', sa.String(length=50), nullable=True, comment='Tempo estimado de percurso (Google Maps)'))
    op.add_column('logistics_timeline', sa.Column('location_place_id', sa.String(length=255), nullable=True, comment='Google Place ID para precisão de localização'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics_timeline', 'location_place_id')
    op.drop_column('logistics_timeline', 'route_duration')
    op.drop_column('logistics_timeline', 'route_distance')
    op.drop_column('logistics_timeline', 'weather_condition')
    op.drop_column('logistics_timeline', 'weather_temp')
    # ### end Alembic commands ###
