"""create_saas_payment_logs_table

Revision ID: 87fbaf251c4b
Revises: cf941776a270
Create Date: 2026-02-25 21:32:43.390813
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = '87fbaf251c4b'
down_revision: str | None = 'cf941776a270'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_payment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_payment_logs_event_type'), 'saas_payment_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_saas_payment_logs_payment_id'), 'saas_payment_logs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_saas_payment_logs_tenant_id'), 'saas_payment_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saas_payment_logs_tenant_id'), table_name='saas_payment_logs')
    op.drop_index(op.f('ix_saas_payment_logs_payment_id'), table_name='saas_payment_logs')
    op.drop_index(op.f('ix_saas_payment_logs_event_type'), table_name='saas_payment_logs')
    op.drop_table('saas_payment_logs')
    # ### end Alembic commands ###
