"""add_onboarded_to_tenant

Revision ID: c13cd8d9de5d
Revises: 323c2aa8f611
Create Date: 2026-02-27 16:08:53.856296
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'c13cd8d9de5d'
down_revision: Union[str, None] = '323c2aa8f611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Adiciona campo is_onboarded ao tenant ###
    op.add_column('tenants', sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_onboarded')
    # ### end Alembic commands ###
