"""fase_16_is_auto_generated

Revision ID: c3ca71e494ff
Revises: 166716aa8cad
Create Date: 2026-02-25 12:54:48.018026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'c3ca71e494ff'
down_revision: Union[str, None] = '166716aa8cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_transactions', sa.Column('is_auto_generated', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Flag que indica se a transação foi gerada automaticamente pelo sistema (ex: Parser de Equipe)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_transactions', 'is_auto_generated')
    # ### end Alembic commands ###
