"""create_system_settings_table

Revision ID: c594c1b01406
Revises: 7684d2a8db28
Create Date: 2026-02-25 21:07:27.158094
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'c594c1b01406'
down_revision: Union[str, None] = '7684d2a8db28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evolution_api_url', sa.String(length=255), nullable=True),
    sa.Column('evolution_api_key', sa.String(length=255), nullable=True),
    sa.Column('evolution_instance_name', sa.String(length=100), nullable=True),
    sa.Column('is_whatsapp_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
