"""create_show_crews_table

Revision ID: cf941776a270
Revises: c594c1b01406
Create Date: 2026-02-25 21:26:27.703249
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = 'cf941776a270'
down_revision: str | None = 'c594c1b01406'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('base_cache', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor padrão de cachê'),
    sa.Column('base_diaria', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor padrão de diária'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_crews_artist_id'), 'artist_crews', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_crews_tenant_id'), 'artist_crews', ['tenant_id'], unique=False)
    op.create_table('show_crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('crew_member_id', sa.UUID(), nullable=False),
    sa.Column('read_receipt', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['artist_crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_crews_crew_member_id'), 'show_crews', ['crew_member_id'], unique=False)
    op.create_index(op.f('ix_show_crews_show_id'), 'show_crews', ['show_id'], unique=False)
    op.create_index(op.f('ix_show_crews_tenant_id'), 'show_crews', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_crews_tenant_id'), table_name='show_crews')
    op.drop_index(op.f('ix_show_crews_show_id'), table_name='show_crews')
    op.drop_index(op.f('ix_show_crews_crew_member_id'), table_name='show_crews')
    op.drop_table('show_crews')
    op.drop_index(op.f('ix_artist_crews_tenant_id'), table_name='artist_crews')
    op.drop_index(op.f('ix_artist_crews_artist_id'), table_name='artist_crews')
    op.drop_table('artist_crews')
    # ### end Alembic commands ###
