"""feat_bi_previsional_fase_25

Revision ID: db9c308341ec
Revises: 527d7823a2c6
Create Date: 2026-02-25 20:03:44.334124
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
"""feat_bi_previsional_fase_25

Revision ID: db9c308341ec
Revises: 527d7823a2c6
Create Date: 2026-02-25 20:03:44.334124
"""



# revision identifiers, used by Alembic
revision: str = 'db9c308341ec'
down_revision: str | None = '527d7823a2c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('logistics_budget_limit', sa.Numeric(precision=14, scale=2), server_default="0", nullable=False, comment='Limite de Budget Logístico (Simulador BI)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'logistics_budget_limit')
    # ### end Alembic commands ###
