"""feat_bi_previsional_fase_25

Revision ID: db9c308341ec
Revises: 527d7823a2c6
Create Date: 2026-02-25 20:03:44.334124
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
"""feat_bi_previsional_fase_25

Revision ID: db9c308341ec
Revises: 527d7823a2c6
Create Date: 2026-02-25 20:03:44.334124
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'db9c308341ec'
down_revision: Union[str, None] = '527d7823a2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('logistics_budget_limit', sa.Numeric(precision=14, scale=2), server_default="0", nullable=False, comment='Limite de Budget Logístico (Simulador BI)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'logistics_budget_limit')
    # ### end Alembic commands ###
