"""Refactor SaaSLead and remove Plan

Revision ID: dbe51a169fbc
Revises: ee10edbdd580
Create Date: 2026-03-04 13:40:55.153009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'dbe51a169fbc'
down_revision: Union[str, None] = 'ee10edbdd580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('plans')
    op.add_column('saas_leads', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('saas_leads', sa.Column('contact_name', sa.String(length=255), nullable=False))
    op.add_column('saas_leads', sa.Column('document', sa.String(length=20), nullable=True))
    op.add_column('saas_leads', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('saas_leads', sa.Column('notes', sa.Text(), nullable=True))
    
    # Criar novo tipo enum explicitamente
    op.execute("CREATE TYPE saas_lead_status_enum AS ENUM ('NOVO', 'CONTATADO', 'QUALIFICADO', 'PROPOSTA', 'CONVERTIDO', 'PERDIDO')")
    
    # Alterar a coluna (o raw SQL é mais robusto para casting entre enums no Postgres)
    op.execute("ALTER TABLE saas_leads ALTER COLUMN status TYPE saas_lead_status_enum USING 'NOVO'::saas_lead_status_enum")

    op.drop_column('saas_leads', 'agency_name')
    op.drop_column('saas_leads', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_leads', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('saas_leads', sa.Column('agency_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('saas_leads', 'status',
               existing_type=sa.Enum('NOVO', 'CONTATADO', 'QUALIFICADO', 'PROPOSTA', 'CONVERTIDO', 'PERDIDO', name='saas_lead_status_enum'),
               type_=postgresql.ENUM('LEAD', 'DEMO', 'TRIAL', 'ASSINANTE', name='saas_lead_status'),
               existing_nullable=False)
    op.drop_column('saas_leads', 'notes')
    op.drop_column('saas_leads', 'source')
    op.drop_column('saas_leads', 'document')
    op.drop_column('saas_leads', 'contact_name')
    op.drop_column('saas_leads', 'company_name')
    op.create_table('plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey'))
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome do escritório/produtora prospectado'),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome do contato principal'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='CNPJ ou CPF'),
    sa.Column('status', postgresql.ENUM('NOVO', 'CONTATADO', 'QUALIFICADO', 'PROPOSTA', 'CONVERTIDO', 'PERDIDO', name='lead_status'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Origem do lead (Site, Indicação, Instagram, etc.)'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Observações sobre o lead'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    # ### end Alembic commands ###
