"""Add saas catalog and tenant limits

Revision ID: e159a83d902c
Revises: ed28defc531a
Create Date: 2026-02-28 12:26:59.859875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'e159a83d902c'
down_revision: Union[str, None] = 'ed28defc531a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_addons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('addon_type', sa.Enum('STORAGE', 'USERS', 'WHATSAPP', name='addon_type_enum'), nullable=False),
    sa.Column('quantity_added', sa.Integer(), nullable=False, comment='Quanto de recurso este addon libera'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saas_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('add_users', sa.Integer(), nullable=False),
    sa.Column('add_storage_gb', sa.Integer(), nullable=False),
    sa.Column('add_whatsapp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenant_subscription_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=True),
    sa.Column('addon_id', sa.UUID(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['saas_addons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bundle_id'], ['saas_bundles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Alterar a tabela tenants para adicionar colunas como nullable primeiro
    op.add_column('tenants', sa.Column('account_type', sa.String(length=50), nullable=True, comment='Perfil do tenant: ARTIST ou AGENCY'))
    op.add_column('tenants', sa.Column('users_limit', sa.Integer(), nullable=True, comment='Limite de usuários na plataforma'))
    op.add_column('tenants', sa.Column('storage_limit_gb', sa.Integer(), nullable=True, comment='Limite total de armazenamento no Minio S3 em GB'))
    op.add_column('tenants', sa.Column('whatsapp_limit', sa.Integer(), nullable=True, comment='Limite de instâncias permitidas na Evolution API'))

    # Preencher valores padrão para registros existentes
    op.execute("UPDATE tenants SET account_type = 'ARTIST' WHERE account_type IS NULL")
    op.execute("UPDATE tenants SET users_limit = 5 WHERE users_limit IS NULL")
    op.execute("UPDATE tenants SET storage_limit_gb = 10 WHERE storage_limit_gb IS NULL")
    op.execute("UPDATE tenants SET whatsapp_limit = 0 WHERE whatsapp_limit IS NULL")

    # Agora sim, tornar NOT NULL
    op.alter_column('tenants', 'account_type', nullable=False)
    op.alter_column('tenants', 'users_limit', nullable=False)
    op.alter_column('tenants', 'storage_limit_gb', nullable=False)
    op.alter_column('tenants', 'whatsapp_limit', nullable=False)

    op.drop_column('tenants', 'max_users')
    op.drop_column('tenants', 'max_storage_gb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('max_storage_gb', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False, comment='Limite de armazenamento em GB'))
    op.add_column('tenants', sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'whatsapp_limit')
    op.drop_column('tenants', 'storage_limit_gb')
    op.drop_column('tenants', 'users_limit')
    op.drop_column('tenants', 'account_type')
    op.drop_table('tenant_subscription_logs')
    op.drop_table('saas_bundles')
    op.drop_table('saas_addons')
    # ### end Alembic commands ###
