"""add address fragment fields to tenant

Revision ID: ed28defc531a
Revises: c13cd8d9de5d
Create Date: 2026-02-27 20:03:34.301573
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'ed28defc531a'
down_revision: Union[str, None] = 'c13cd8d9de5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=False, comment='ID do Clerk do Admin'),
    sa.Column('action', sa.String(length=255), nullable=False, comment="Ex: 'ALTER_TENANT_LIMITS'"),
    sa.Column('target_id', sa.String(length=255), nullable=True, comment='ID do alvo (ex: tenant_id)'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dados da alteração'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saas_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'DEMO', 'TRIAL', 'ASSINANTE', name='saas_lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('financial_transactions', sa.Column('public_payment_status', sa.Enum('PENDING_EMPENHO', 'EMPENHADO', 'LIQUIDADO', 'PAGO', name='public_payment_status'), nullable=True, comment='Status do ciclo de empenho (apenas para mercado público)'))
    op.add_column('financial_transactions', sa.Column('empenho_date', sa.Date(), nullable=True, comment='Data da nota de empenho'))
    op.add_column('financial_transactions', sa.Column('empenho_number', sa.String(length=50), nullable=True, comment='Número da nota de empenho'))
    op.add_column('financial_transactions', sa.Column('liquidation_date', sa.Date(), nullable=True, comment='Data da liquidação'))
    op.alter_column('leads', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do escritório/produtora prospectado',
               existing_comment='Nome do escritório/agência prospectado',
               existing_nullable=False)
    op.add_column('show_crews', sa.Column('token', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_show_crews_token'), 'show_crews', ['token'], unique=True)
    op.add_column('tenants', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('complement', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('neighborhood', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('state', sa.String(length=2), nullable=True))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do escritório/produtora',
               existing_comment='Nome do escritório/agência',
               existing_nullable=False)
    op.alter_column('tenants', 'document',
               existing_type=sa.VARCHAR(length=20),
               comment='Antigo identificador (CPF/CNPJ)',
               existing_comment='CNPJ ou CPF do escritório',
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'TRIAL', name='tenant_status'),
               comment=None,
               existing_comment='Status da assinatura SaaS',
               existing_nullable=False)
    op.alter_column('tenants', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Nível do plano (Essencial, Pro, Enterprise)',
               existing_nullable=False,
               existing_server_default=sa.text("'Essencial'::character varying"))
    op.alter_column('tenants', 'feature_toggles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Toggles de recursos (JSONB)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenants', 'max_users',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Limite máximo de usuários permitidos no plano',
               existing_nullable=False)
    op.alter_column('tenants', 'max_storage_gb',
               existing_type=sa.INTEGER(),
               comment='Limite de armazenamento em GB',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('tenants', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               comment='Kill Switch: Se True, bloqueia acesso',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='E-mail principal de contato',
               existing_nullable=True)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('tenants', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               comment='Indica se o tenant completou o wizard inicial',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'subscription_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de vencimento da assinatura (renovada a cada pagamento)',
               existing_nullable=True)
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Produtora que abriu o chamado',
               existing_comment='Agência que abriu o chamado',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Agência que abriu o chamado',
               existing_comment='Produtora que abriu o chamado',
               existing_nullable=False)
    op.alter_column('tenants', 'subscription_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de vencimento da assinatura (renovada a cada pagamento)',
               existing_nullable=True)
    op.alter_column('tenants', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica se o tenant completou o wizard inicial',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail principal de contato',
               existing_nullable=True)
    op.alter_column('tenants', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Kill Switch: Se True, bloqueia acesso',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenants', 'max_storage_gb',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Limite de armazenamento em GB',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('tenants', 'max_users',
               existing_type=sa.INTEGER(),
               comment='Limite máximo de usuários permitidos no plano',
               existing_nullable=False)
    op.alter_column('tenants', 'feature_toggles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Toggles de recursos (JSONB)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenants', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nível do plano (Essencial, Pro, Enterprise)',
               existing_nullable=False,
               existing_server_default=sa.text("'Essencial'::character varying"))
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'TRIAL', name='tenant_status'),
               comment='Status da assinatura SaaS',
               existing_nullable=False)
    op.alter_column('tenants', 'document',
               existing_type=sa.VARCHAR(length=20),
               comment='CNPJ ou CPF do escritório',
               existing_comment='Antigo identificador (CPF/CNPJ)',
               existing_nullable=True)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do escritório/agência',
               existing_comment='Nome do escritório/produtora',
               existing_nullable=False)
    op.drop_column('tenants', 'state')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'neighborhood')
    op.drop_column('tenants', 'complement')
    op.drop_column('tenants', 'number')
    op.drop_column('tenants', 'street')
    op.drop_column('tenants', 'cep')
    op.drop_index(op.f('ix_show_crews_token'), table_name='show_crews')
    op.drop_column('show_crews', 'token')
    op.alter_column('leads', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do escritório/agência prospectado',
               existing_comment='Nome do escritório/produtora prospectado',
               existing_nullable=False)
    op.drop_column('financial_transactions', 'liquidation_date')
    op.drop_column('financial_transactions', 'empenho_number')
    op.drop_column('financial_transactions', 'empenho_date')
    op.drop_column('financial_transactions', 'public_payment_status')
    op.drop_table('saas_leads')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
