"""update_tenant_plan_fk_to_bundles

Revision ID: ee10edbdd580
Revises: e159a83d902c
Create Date: 2026-02-28 13:28:45.074717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'ee10edbdd580'
down_revision: Union[str, None] = 'e159a83d902c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenants_plan_id_fkey'), 'tenants', type_='foreignkey')
    
    # Limpar IDs de planos antigos que não existem na nova tabela saas_bundles
    op.execute("UPDATE tenants SET plan_id = NULL")
    
    op.create_foreign_key(None, 'tenants', 'saas_bundles', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_plan_id_fkey'), 'tenants', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###
