"""initial_schema

Revision ID: f2ef7a1580d7
Revises: 
Create Date: 2026-02-23 16:30:31.986598
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'f2ef7a1580d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do escritório/agência'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CNPJ ou CPF do escritório'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='E-mail principal de contato'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefone de contato'),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TRIAL', name='tenant_status'), nullable=False, comment='Status da assinatura SaaS'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Limite máximo de usuários permitidos no plano'),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Data de vencimento da assinatura (renovada a cada pagamento)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome artístico'),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Razão social / Nome legal para contratos'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CNPJ ou CPF do artista/empresa'),
    sa.Column('genre', sa.String(length=100), nullable=True, comment='Gênero musical principal (Sertanejo, Funk, etc.)'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Biografia resumida para contratos e propostas'),
    sa.Column('photo_url', sa.String(length=500), nullable=True, comment='URL da foto principal do artista'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_tenant_id'), 'artists', ['tenant_id'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do contratante (pessoa física ou jurídica)'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='CNPJ ou CPF do contratante'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True, comment='Cidade do contratante'),
    sa.Column('uf', sa.String(length=2), nullable=True, comment='UF do contratante'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_tenant_id'), 'contractors', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome do perfil (ex: Admin, Produtor, Músico)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descrição do perfil de permissões'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Matriz JSONB de permissões granulares'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do local (ex: Arena Castelão, Bar do Zé)'),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Endereço completo'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Capacidade de público'),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_tenant_id'), 'venues', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False, comment='ID único do usuário no Clerk (provedor de auth)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='E-mail do usuário'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome completo do usuário'),
    sa.Column('role_id', sa.UUID(), nullable=True, comment='Perfil RBAC do usuário'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Se False, o usuário está desativado e não pode acessar a API'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False, comment='Artista que se apresenta neste show'),
    sa.Column('contractor_id', sa.UUID(), nullable=True, comment='Contratante do show (pode ser cadastrado on-the-fly)'),
    sa.Column('venue_id', sa.UUID(), nullable=True, comment='Local/Casa de Show (pode ser cadastrado on-the-fly)'),
    sa.Column('status', sa.Enum('SONDAGEM', 'PROPOSTA', 'CONTRATO_PENDENTE', 'ASSINADO', 'PRE_PRODUCAO', 'EM_ESTRADA', 'CONCLUIDO', name='show_status'), nullable=False, comment='Etapa atual na esteira de produção'),
    sa.Column('client_type', sa.Enum('PRIVATE', 'PUBLIC', name='client_type'), nullable=False, comment='Tipo de show: PRIVATE ou PUBLIC (Prefeitura)'),
    sa.Column('negotiation_type', sa.Enum('CACHE_DESPESAS', 'COLOCADO_CIDADE', 'COLOCADO_TOTAL', 'PERSONALIZADO', name='negotiation_type'), nullable=False, comment='Filtro de negociação: define quem paga o quê'),
    sa.Column('custom_negotiation_notes', sa.Text(), nullable=True, comment='Notas adicionais quando negotiation_type == PERSONALIZADO'),
    sa.Column('date_show', sa.Date(), nullable=False, comment='Data do show'),
    sa.Column('date_end', sa.Date(), nullable=True, comment='Data de término (para temporadas/festivais multi-dia)'),
    sa.Column('location_city', sa.String(length=255), nullable=False, comment='Cidade do show'),
    sa.Column('location_uf', sa.String(length=2), nullable=False, comment='UF (estado) do show'),
    sa.Column('location_venue_name', sa.String(length=255), nullable=True, comment='Nome do local/casa de show (texto livre)'),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor de Face (Nota) — para Prefeituras é o valor público'),
    sa.Column('real_cache', sa.Numeric(precision=14, scale=2), nullable=False, comment='Cachê Real — receita efetiva da produtora'),
    sa.Column('production_kickback', sa.Numeric(precision=14, scale=2), nullable=False, comment='Retorno de Produção (Prefeitura) — NUNCA contabilizar como lucro no DRE'),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentual de imposto sobre a Nota Fiscal'),
    sa.Column('contract_validated', sa.Boolean(), nullable=False, comment='TRAVA MESTRA: Se False, bloqueia Etapa 3 (Pré-Produção/Logística)'),
    sa.Column('contract_validated_at', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da validação do contrato'),
    sa.Column('contract_validated_by', sa.UUID(), nullable=True, comment='Usuário que validou o contrato'),
    sa.Column('road_closed', sa.Boolean(), nullable=False, comment='Se True, check-in da equipe realizado — libera consolidação do DRE'),
    sa.Column('road_closed_at', sa.DateTime(timezone=True), nullable=True, comment='Data/hora do fechamento de estrada'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações gerais sobre o show'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_artist_id'), 'shows', ['artist_id'], unique=False)
    op.create_index(op.f('ix_shows_status'), 'shows', ['status'], unique=False)
    op.create_index(op.f('ix_shows_tenant_id'), 'shows', ['tenant_id'], unique=False)
    op.create_table('city_base_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=True, comment='Show de origem deste registro de custo (se aplicável)'),
    sa.Column('city', sa.String(length=255), nullable=False, comment='Cidade de destino'),
    sa.Column('uf', sa.String(length=2), nullable=False, comment='UF da cidade'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Categoria do custo (FLIGHT, HOTEL, VAN_TRANSFER, etc.)'),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor do custo registrado'),
    sa.Column('reference_date', sa.Date(), nullable=False, comment='Data de referência do custo (para filtro de últimos 12 meses)'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_base_costs_city'), 'city_base_costs', ['city'], unique=False)
    op.create_index(op.f('ix_city_base_costs_tenant_id'), 'city_base_costs', ['tenant_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Usuário do sistema que recebe a comissão (se interno)'),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=False, comment='Nome do beneficiário (pode ser externo, não-usuário)'),
    sa.Column('commission_base', sa.Enum('GROSS', 'NET', name='commission_base'), nullable=False, comment='Base de cálculo: GROSS (sobre bruto) ou NET (sobre líquido)'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentual da comissão (ex: 10.00 para 10%)'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_show_id'), 'commissions', ['show_id'], unique=False)
    op.create_index(op.f('ix_commissions_tenant_id'), 'commissions', ['tenant_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SIGNED', 'CANCELLED', name='contract_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título do contrato (ex: Minuta Principal, Aditivo 01)'),
    sa.Column('content', sa.Text(), nullable=True, comment='Conteúdo/corpo da minuta em texto (para geração PDF futura)'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='URL do documento assinado (upload manual ou assinatura digital)'),
    sa.Column('signed_by', sa.String(length=255), nullable=True, comment='Nome de quem assinou o contrato'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_show_id'), 'contracts', ['show_id'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False, comment='Show ao qual esta transação pertence'),
    sa.Column('type', sa.Enum('REVENUE', 'PRODUCTION_COST', 'LOGISTICS_COST', 'TAX', 'COMMISSION', 'KICKBACK', 'EXTRA_EXPENSE', name='transaction_type'), nullable=False, comment='Tipo macro da transação (Receita, Custo de Produção, etc.)'),
    sa.Column('category', sa.Enum('CREW_PAYMENT', 'BACKLINE', 'SOUND_LIGHT', 'STAGE', 'FLIGHT', 'BUS', 'HOTEL', 'VAN_TRANSFER', 'MEALS', 'TAX_NF', 'INTERMEDIARY', 'OTHER', name='transaction_category'), nullable=False, comment='Categoria detalhada do custo'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descrição livre do lançamento'),
    sa.Column('budgeted_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor orçado/previsto (definido na Etapa 1 ou 3)'),
    sa.Column('realized_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor real pago/executado'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='URL do comprovante/nota fiscal (upload via S3 no app mobile)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_show_id'), 'financial_transactions', ['show_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_id'), 'financial_transactions', ['tenant_id'], unique=False)
    op.create_table('logistics_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False, comment='Horário do item na timeline (ex: 14:00)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título do item (ex: Chegada no Aeroporto, Passagem de Som)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detalhes adicionais (endereço, contato, observações)'),
    sa.Column('icon_type', sa.String(length=50), nullable=True, comment='Tipo de ícone para o frontend (flight, hotel, soundcheck, show, etc.)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Ordem de exibição na timeline'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_timeline_show_id'), 'logistics_timeline', ['show_id'], unique=False)
    op.create_index(op.f('ix_logistics_timeline_tenant_id'), 'logistics_timeline', ['tenant_id'], unique=False)
    op.create_table('show_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Membro da equipe que fez check-in'),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data/hora do check-in'),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_checkins_show_id'), 'show_checkins', ['show_id'], unique=False)
    op.create_index(op.f('ix_show_checkins_tenant_id'), 'show_checkins', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_checkins_tenant_id'), table_name='show_checkins')
    op.drop_index(op.f('ix_show_checkins_show_id'), table_name='show_checkins')
    op.drop_table('show_checkins')
    op.drop_index(op.f('ix_logistics_timeline_tenant_id'), table_name='logistics_timeline')
    op.drop_index(op.f('ix_logistics_timeline_show_id'), table_name='logistics_timeline')
    op.drop_table('logistics_timeline')
    op.drop_index(op.f('ix_financial_transactions_tenant_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_show_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_show_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_commissions_tenant_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_show_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_city_base_costs_tenant_id'), table_name='city_base_costs')
    op.drop_index(op.f('ix_city_base_costs_city'), table_name='city_base_costs')
    op.drop_table('city_base_costs')
    op.drop_index(op.f('ix_shows_tenant_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_status'), table_name='shows')
    op.drop_index(op.f('ix_shows_artist_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_venues_tenant_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_contractors_tenant_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_artists_tenant_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_table('tenants')
    # ### end Alembic commands ###
